package main

import (
	"strings"
	"testing"

	"host-health-mcp/daemon/internal/shared/capsplan"
)

func TestRenderCapsFormat(t *testing.T) {
	p := capsplan.For([]string{"firewall"}, nil, nil)
	got := renderCaps("/etc/host-health-mcp/manifest.yml", p)
	want := "# Auto-generated by /usr/sbin/host-health-mcp-caps-template\n" +
		"# from /etc/host-health-mcp/manifest.yml.\n" +
		"# Edit /etc/host-health-mcp/manifest.yml and re-run the generator to refresh.\n" +
		"[Service]\n" +
		"CapabilityBoundingSet=CAP_CHOWN CAP_NET_ADMIN \n" +
		"AmbientCapabilities=CAP_NET_ADMIN \n"
	if got != want {
		t.Errorf("render mismatch:\n got %q\nwant %q", got, want)
	}
}

// An empty ambient set must still emit the key. Omitting the line
// would leave whatever a previous drop-in set in force.
func TestRenderCapsEmptyAmbientStillEmitsTheKey(t *testing.T) {
	got := renderCaps("/m.yml", capsplan.For(nil, nil, nil))
	if !strings.Contains(got, "\nAmbientCapabilities=\n") {
		t.Errorf("empty ambient must still emit the key, got:\n%s", got)
	}
}

func TestRenderIPFilter(t *testing.T) {
	got := renderIPFilter("/etc/host-health-mcp/daemon.yml", []string{"192.0.2.0/24", "localhost"})
	want := "# Auto-generated by /usr/sbin/host-health-mcp-caps-template\n" +
		"# from /etc/host-health-mcp/daemon.yml (ip_filter_allow).\n" +
		"# NOTE: these rules apply to inbound AND outbound packets.\n" +
		"[Service]\n" +
		"IPAddressDeny=any\n" +
		"IPAddressAllow=192.0.2.0/24\n" +
		"IPAddressAllow=localhost\n"
	if got != want {
		t.Errorf("render mismatch:\n got %q\nwant %q", got, want)
	}
}
